service: mariadb_master
repo: docker.io/bitnami/mariadb
tag: latest
ports:
  - 3306:3306
volumes:
user:
env:
    MARIADB_ROOT_PASSWORD: "password123"
    MARIADB_REPLICATION_MODE: "master" 
    MARIADB_REPLICATION_USER: "my_repl_user" 
    MARIADB_REPLICATION_PASSWORD: "my_repl_password" 
    MARIADB_USER: "my_user" 
    MARIADB_PASSWORD: "my_password"
    MARIADB_DATABASE: "my_database"
    MARIADB_PORT_NUMBER: 3306