---
 - name: Install python setup tools
   yum: name=python-setuptools

 - name: Install Pypi
   easy_install: name=pip

 - name: Install docker pip
   pip: name=docker 

 - name: Install Docker
   yum: name=docker state=latest
 
 - name: Make sure Docker daemon is running
   service: name=docker state=started

 - name: Create a docker network
   docker_network:
     name: pipl