service: kibana
repo: docker.elastic.co/kibana/kibana
tag: 6.4.2
conf_dir: "/usr/share/kibana/config/"
conf_files:
  - kibana.yml
ports:
  - 5061:5061
volumes:
  - "{{ docker_dir }}/{{ service }}/:{{ conf_dir }}"
user: kibana